// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzpjynuwxcwyzhmumlcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cGp5bnV3eGN3eXpobXVtbGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTE0NjMsImV4cCI6MjA3MTI2NzQ2M30.Y8ZnQX58UIFEsHHRINl1yp-2lW2Ar8Vp5Dp4Ief76gM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});